### PR TITLE
Adding some metrics computation

### PR DESCRIPTION
**Pull request by oumaziz**

### CODE REVIEW

**Comment by jrfaller** [comment]
I added comment directly in the diff

**Comment by oumaziz** [comment]
You are right, those lines are useless. They were used for debugging purposes, forgot to remove them.

**Comment by oumaziz** [comment]
Thank you for the suggestions, i updated the code

**Comment by oumaziz** [comment]
Just fixed it, anything else ?

**Comment by jrfaller** [comment]
No this is good, I will merge it.

**Pull request merged**
